### ISSUE TITLE
404 (Not Found) on 1.0.0

### ISSUE THREAD

**Issue by TiagoGouvea** [rollbar/github-deploy-action#1]
I'm testing the new Rollbar action and faced the following error:

```
Failed to download action 'https://api.github.com/repos/rollbar/github-deploy-action/tarball/1.0.0'. 
Error Response status code does not indicate success: 404 (Not Found)
```

I don't know but seams that it's just missing a "v" on the URL, it should be
```
https://api.github.com/repos/rollbar/github-deploy-action/tarball/v1.0.0
```

My action is public [here](https://github.com/TiagoGouvea/resources4vulnerable/actions/runs/79173523).

Thank you

**Comment by basoko** [comment]
Hi @TiagoGouvea !

I think that we have a type in the docs then. Could you please try changing this line:

```
 uses: rollbar/github-deploy-action@1.0.0
```

to 

```
 uses: rollbar/github-deploy-action@v1.0.0
```
Thanks!

**Comment by basoko** [comment]
@TiagoGouvea I've published a `1.0.0` tag pointing to the same commit that does `v1.0.0`, so it should work now with both values.

**Comment by TiagoGouvea** [comment]
I think I was the first to use it. :)

Thank you for the clarification, it work perfect now.

**Comment by basoko** [comment]
Glad to hear it's working, and you are using it! :)

Thanks!
