### ISSUE TITLE
Workflow fail, when Rollbar is on maintenance

### ISSUE THREAD

**Issue by TiagoGouvea** [rollbar/github-deploy-action#6]
Yesterday some of my deployments failed, and when I checked, it was on `rollbar/github-deploy-action`.

I went to Rollbar website and saw that it was on maintenance, this way, the action didn't receive the response and failed.

A suggestion would be to add an option to continue, even without rollbar response. 

I for a native good way to do that on GitHub Action but didn't found.

**Comment by gavinsharp** [comment]
> I for a native good way to do that on GitHub Action but didn't found.

I believe you could accomplish this using [`jobs.<job_id>.steps.continue-on-error`](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error).

**Comment by TiagoGouvea** [comment]
Good catch @gavinsharp . I didn't know about this option. I will use it. Thanks!
